export type GlossaryTerm = {
  term: string;
  definition: string;
  slug: string;
  relatedArticles?: string[]; // Slugs of related articles
};

const glossaryTermsIt: GlossaryTerm[] = [
  {
    term: "AGEs",
    slug: "ages",
    definition: "Advanced Glycation End-products (Prodotti Finali della Glicazione Avanzata). Composti dannosi che si formano quando proteine o grassi si legano allo zucchero nel sangue. Contribuiscono all'invecchiamento e alle malattie croniche.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "ApoB",
    slug: "apob",
    definition: "Apolipoproteina B. La proteina principale presente nelle particelle di colesterolo 'cattivo' (LDL, VLDL). È considerata un indicatore più preciso del rischio cardiovascolare rispetto al solo colesterolo LDL.",
    relatedArticles: ["biomarker-longevita-guida"],
  },
  {
    term: "Autofagia",
    slug: "autofagia",
    definition: "Un processo cellulare di 'pulizia' in cui la cellula degrada e ricicla i propri componenti danneggiati o non necessari. È fondamentale per il rinnovamento cellulare e la longevità.",
    relatedArticles: ["digiuno-intermittente-autofagia", "dieta-mima-digiuno-fmd"],
  },
  {
    term: "Blue Zones",
    slug: "blue-zones",
    definition: "Regioni del mondo (come la Sardegna o Okinawa) dove le persone vivono molto più a lungo della media. Lo studio di queste zone ha rivelato abitudini comuni legate alla longevità.",
    relatedArticles: [],
  },
  {
    term: "Chetoni",
    slug: "chetoni",
    definition: "Molecole prodotte dal fegato a partire dai grassi quando la disponibilità di glucosio è scarsa (digiuno, dieta chetogenica). Forniscono un'energia efficiente per il cervello e il corpo.",
    relatedArticles: ["digiuno-intermittente-autofagia"],
  },
  {
    term: "Cortisolo",
    slug: "cortisolo",
    definition: "Un ormone steroideo prodotto dalle ghiandole surrenali in risposta allo stress. Livelli cronicamente elevati possono avere effetti negativi su metabolismo, sistema immunitario e salute mentale.",
    relatedArticles: ["cortisolo-stress-cronico", "ritmo-circadiano-master-clock"],
  },
  {
    term: "Disbiosi",
    slug: "disbiosi",
    definition: "Uno squilibrio nella composizione o nella funzione del microbioma, spesso associato a disturbi gastrointestinali, infiammazione e altre patologie.",
    relatedArticles: ["gut-health-microbioma", "microbioma"],
  },
  {
    term: "EPOC",
    slug: "epoc",
    definition: "Excess Post-exercise Oxygen Consumption. Il fenomeno per cui il corpo continua a bruciare calorie a un tasso elevato anche dopo la fine dell'allenamento per ripristinare l'equilibrio fisiologico.",
    relatedArticles: ["esercizio-massimizzare-risultati"],
  },
  {
    term: "EVO",
    slug: "evo",
    definition: "Extra Vergine di Oliva. L'olio d'oliva di qualità superiore, ottenuto unicamente mediante procedimenti meccanici. Ricco di polifenoli e grassi monoinsaturi benefici.",
    relatedArticles: ["dieta-mima-digiuno-schema-5-giorni"],
  },
  {
    term: "FMD",
    slug: "fmd",
    definition: "Fasting Mimicking Diet (Dieta Mima Digiuno). Un protocollo alimentare a basso contenuto calorico e proteico progettato per indurre gli effetti benefici del digiuno (come l'autofagia) pur continuando a mangiare.",
    relatedArticles: ["dieta-mima-digiuno-fmd"],
  },
  {
    term: "Fruttosio",
    slug: "fruttosio",
    definition: "Uno zucchero semplice presente naturalmente nella frutta. A differenza del glucosio, viene metabolizzato quasi esclusivamente dal fegato. Un eccesso (da zuccheri aggiunti) può causare fegato grasso.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "GABA",
    slug: "gaba",
    definition: "Acido Gamma-Amminobutirrico. Il principale neurotrasmettitore inibitorio del cervello, responsabile del rilassamento e della riduzione dell'eccitabilità neuronale.",
    relatedArticles: ["gut-health-microbioma", "12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Glicazione",
    slug: "glicazione",
    definition: "Un processo in cui lo zucchero in eccesso nel sangue si lega alle proteine, danneggiandole e compromettendone la funzione. È una delle cause principali dell'invecchiamento dei tessuti.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "Glucosio",
    slug: "glucosio",
    definition: "La principale fonte di energia per le cellule del corpo. Viene trasportato nel sangue e la sua concentrazione è regolata dall'insulina.",
    relatedArticles: ["miti-zuccheri", "insulina-resistenza-metabolismo"],
  },
  {
    term: "GLUT4",
    slug: "glut4",
    definition: "Una proteina che trasporta il glucosio dal sangue all'interno delle cellule muscolari e adipose. L'esercizio fisico può attivare i GLUT4 indipendentemente dall'insulina.",
    relatedArticles: ["insulina-resistenza-metabolismo", "esercizio-massimizzare-risultati"],
  },
  {
    term: "HbA1c",
    slug: "hba1c",
    definition: "Emoglobina Glicata. Un test che misura la media dei livelli di zucchero nel sangue negli ultimi 3 mesi, offrendo una visione a lungo termine del controllo glicemico.",
    relatedArticles: ["biomarker-longevita-guida", "insulina-resistenza-metabolismo"],
  },
  {
    term: "HIIT",
    slug: "hiit",
    definition: "High Intensity Interval Training. Una forma di allenamento cardiovascolare che alterna brevi periodi di esercizio anaerobico intenso a periodi di recupero meno intensi.",
    relatedArticles: ["esercizio-massimizzare-risultati", "hrv-vo2-rhr-guida"],
  },
  {
    term: "HOMA-IR",
    slug: "homa-ir",
    definition: "Homeostatic Model Assessment for Insulin Resistance. Un indice utilizzato per stimare la resistenza all'insulina e la funzione delle cellule beta del pancreas.",
    relatedArticles: ["insulina-resistenza-metabolismo"],
  },
  {
    term: "HRV",
    slug: "hrv",
    definition: "Heart Rate Variability (Variabilità della Frequenza Cardiaca). La variazione nell'intervallo di tempo tra battiti cardiaci consecutivi. È un indicatore chiave dello stato del sistema nervoso autonomo e del recupero.",
    relatedArticles: ["hrv-vo2-rhr-guida", "gadget-sonno-tracker"],
  },
  {
    term: "hs-CRP",
    slug: "hs-crp",
    definition: "High-sensitivity C-reactive Protein. Una proteina prodotta dal fegato che aumenta in presenza di infiammazione. La versione ad alta sensibilità è usata per valutare il rischio cardiovascolare.",
    relatedArticles: ["biomarker-longevita-guida"],
  },
  {
    term: "IGF-1",
    slug: "igf-1",
    definition: "Insulin-like Growth Factor 1. Un ormone simile all'insulina che regola la crescita cellulare. Livelli ridotti sono associati a una maggiore longevità in molti organismi modello.",
    relatedArticles: ["dieta-mima-digiuno-fmd", "miti-proteine"],
  },
  {
    term: "Indice Glicemico",
    slug: "indice-glicemico",
    definition: "Un valore che indica quanto rapidamente un alimento contenente carboidrati fa aumentare i livelli di glucosio nel sangue rispetto al glucosio puro.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "Insulina Resistenza",
    slug: "insulina-resistenza",
    definition: "Una condizione in cui le cellule del corpo non rispondono adeguatamente all'insulina, portando a livelli elevati di glucosio nel sangue e aumentando il rischio di diabete di tipo 2.",
    relatedArticles: ["insulina-resistenza-metabolismo"],
  },
  {
    term: "Lipogenesi de novo",
    slug: "lipogenesi-de-novo",
    definition: "Il processo metabolico attraverso il quale il fegato converte l'eccesso di carboidrati (soprattutto fruttosio) in nuovi acidi grassi, contribuendo al fegato grasso.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "MACs",
    slug: "macs",
    definition: "Microbiota Accessible Carbohydrates. Carboidrati complessi (fibre) che non vengono digeriti dall'ospite ma sono fermentabili dai batteri intestinali, promuovendo un microbioma sano.",
    relatedArticles: ["gut-health-microbioma", "miti-fibre"],
  },
  {
    term: "MED",
    slug: "med",
    definition: "Minimum Effective Dose (Dose Minima Efficace). Il concetto di trovare la quantità minima di uno stimolo (come l'esercizio fisico o un integratore) necessaria per ottenere il risultato desiderato, massimizzando l'efficienza e riducendo lo stress inutile.",
    relatedArticles: ["esercizio-massimizzare-risultati"],
  },
  {
    term: "Microbioma",
    slug: "microbioma",
    definition: "L'insieme di microrganismi (batteri, virus, funghi) che vivono in un determinato ambiente, come l'intestino umano. Svolge un ruolo cruciale nella digestione, nel sistema immunitario e nella sintesi di vitamine.",
    relatedArticles: ["microbioma", "gut-health-microbioma"],
  },
  {
    term: "Mitocondri",
    slug: "mitocondri",
    definition: "Le 'centrali elettriche' delle cellule. Organelli responsabili della produzione di energia (ATP). La loro salute ed efficienza diminuiscono con l'età, ma possono essere potenziate con l'esercizio e la dieta.",
    relatedArticles: ["esercizio-massimizzare-risultati", "hrv-vo2-rhr-guida"],
  },
  {
    term: "mTOR",
    slug: "mtor",
    definition: "mammalian Target of Rapamycin. Una proteina che funge da sensore centrale dei nutrienti, regolando la crescita cellulare e la sintesi proteica. La sua inibizione è legata all'autofagia e alla longevità.",
    relatedArticles: ["dieta-mima-digiuno-fmd", "miti-proteine"],
  },
  {
    term: "NAD+",
    slug: "nad-plus",
    definition: "Nicotinamide Adenina Dinucleotide. Un coenzima essenziale presente in tutte le cellule viventi. È cruciale per il metabolismo energetico e per l'attività delle sirtuine. I suoi livelli diminuiscono con l'età.",
    relatedArticles: [],
  },
  {
    term: "NAFLD",
    slug: "nafld",
    definition: "Non-Alcoholic Fatty Liver Disease (Steatosi Epatica Non Alcolica). L'accumulo di grasso nel fegato non causato dall'alcol, spesso dovuto a un eccesso di fruttosio e insulino-resistenza.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "Nervo Vago",
    slug: "nervo-vago",
    definition: "Il decimo nervo cranico e il componente principale del sistema nervoso parasimpatico. Collega il cervello a cuore, polmoni e intestino, regolando la frequenza cardiaca, la digestione e l'infiammazione.",
    relatedArticles: ["respirazione-biologia-scienza", "hrv-vo2-rhr-guida"],
  },
  {
    term: "Onde Alpha",
    slug: "onde-alpha",
    definition: "Onde cerebrali (8-13 Hz) associate a uno stato di veglia rilassata, calma e 'flow' leggero. Si attivano chiudendo gli occhi e rilassandosi.",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "Onde Beta",
    slug: "onde-beta",
    definition: "Onde cerebrali (13-30 Hz) tipiche dello stato di veglia attiva, attenzione focalizzata e pensiero logico. Se eccessive, possono indicare ansia.",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "Onde Delta",
    slug: "onde-delta",
    definition: "Onde cerebrali lente (0.5-4 Hz) dominanti durante il sonno profondo senza sogni. Fondamentali per la rigenerazione fisica e il rilascio dell'ormone della crescita.",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "Onde Gamma",
    slug: "onde-gamma",
    definition: "Le onde cerebrali più veloci (30-100 Hz), associate a picchi di concentrazione, insight, apprendimento complesso e memoria.",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "Onde Theta",
    slug: "onde-theta",
    definition: "Onde cerebrali (4-8 Hz) legate al rilassamento profondo, alla meditazione, alla creatività e alla fase REM del sonno.",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "ORAC",
    slug: "orac",
    definition: "Oxygen Radical Absorbance Capacity. Un metodo di misurazione della capacità antiossidante di alimenti e sostanze biologiche.",
    relatedArticles: ["cibi-processati-impatto"],
  },
  {
    term: "Ormesi",
    slug: "ormesi",
    definition: "Un fenomeno biologico in cui l'esposizione a basse dosi di un agente stressante (come il freddo, il calore o l'esercizio fisico) stimola risposte adattative benefiche che rafforzano l'organismo.",
    relatedArticles: ["sauna-longevita-calore"],
  },
  {
    term: "Ossido Nitrico",
    slug: "ossido-nitrico",
    definition: "Una molecola gassosa prodotta nei seni paranasali (e nell'endotelio). È un potente vasodilatatore, migliora l'assorbimento di ossigeno e ha proprietà antimicrobiche.",
    relatedArticles: ["respirazione-biologia-scienza"],
  },
  {
    term: "Polifenoli",
    slug: "polifenoli",
    definition: "Composti naturali presenti nelle piante con potenti proprietà antiossidanti e antinfiammatorie. Molti polifenoli agiscono anche come prebiotici.",
    relatedArticles: ["gut-health-microbioma"],
  },
  {
    term: "Prebiotici",
    slug: "prebiotici",
    definition: "Sostanze non digeribili (spesso fibre) che stimolano selettivamente la crescita e/o l'attività di uno o più batteri nel colon, migliorando la salute dell'ospite.",
    relatedArticles: ["gut-health-microbioma"],
  },
  {
    term: "Probiotici",
    slug: "probiotici",
    definition: "Microrganismi vivi che, se somministrati in quantità adeguate, conferiscono un beneficio alla salute dell'ospite.",
    relatedArticles: ["gut-health-microbioma", "guida-integratori"],
  },
  {
    term: "Radicali Liberi",
    slug: "radicali-liberi",
    definition: "Molecole instabili prodotte durante il metabolismo o da fattori esterni (inquinamento, raggi UV). Possono danneggiare le cellule (stress ossidativo) se non neutralizzati dagli antiossidanti.",
    relatedArticles: ["cibi-processati-impatto"],
  },
  {
    term: "RHR",
    slug: "rhr",
    definition: "Resting Heart Rate (Frequenza Cardiaca a Riposo). Il numero di battiti del cuore al minuto quando il corpo è a completo riposo. Un RHR più basso indica generalmente una migliore efficienza cardiovascolare.",
    relatedArticles: ["hrv-vo2-rhr-guida"],
  },
  {
    term: "Saccarosio",
    slug: "saccarosio",
    definition: "Il comune zucchero da tavola. È un disaccaride composto da una molecola di glucosio e una di fruttosio legate insieme.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "SCFA",
    slug: "scfa",
    definition: "Short Chain Fatty Acids (Acidi Grassi a Catena Corta). Prodotti dalla fermentazione batterica delle fibre nell'intestino. Sono fondamentali per la salute del colon e il metabolismo.",
    relatedArticles: ["gut-health-microbioma", "miti-fibre"],
  },
  {
    term: "SCN",
    slug: "scn",
    definition: "Nucleo Soprachiasmatico. Una piccola regione dell'ipotalamo che funge da 'orologio mastro' del corpo, coordinando i ritmi circadiani in risposta alla luce.",
    relatedArticles: ["ritmo-circadiano-master-clock"],
  },
  {
    term: "Senescenza Cellulare",
    slug: "senescenza-cellulare",
    definition: "Uno stato in cui le cellule smettono di dividersi ma non muoiono. Queste 'cellule zombie' accumulano danni e secernono sostanze infiammatorie che danneggiano i tessuti vicini.",
    relatedArticles: [],
  },
  {
    term: "Sindrome Metabolica",
    slug: "sindrome-metabolica",
    definition: "Un cluster di condizioni (pressione alta, glicemia alta, eccesso di grasso addominale, colesterolo anomalo) che aumentano il rischio di malattie cardiache, ictus e diabete.",
    relatedArticles: ["miti-zuccheri", "insulina-resistenza-metabolismo"],
  },
  {
    term: "Sirtuine",
    slug: "sirtuine",
    definition: "Una famiglia di proteine (SIRT1-7) che regolano la salute cellulare, la riparazione del DNA e il metabolismo. La loro attività è stimolata dal NAD+ e da pratiche come il digiuno.",
    relatedArticles: ["dieta-mima-digiuno-fmd"],
  },
  {
    term: "Stress Ossidativo",
    slug: "stress-ossidativo",
    definition: "Uno squilibrio tra la produzione di radicali liberi e la capacità del corpo di neutralizzarli con gli antiossidanti. È una causa chiave dell'invecchiamento e di molte malattie.",
    relatedArticles: ["miti-zuccheri", "cibi-processati-impatto"],
  },
  {
    term: "Telomeri",
    slug: "telomeri",
    definition: "Le estremità protettive dei cromosomi. Si accorciano ogni volta che una cellula si divide e la loro lunghezza è considerata un indicatore dell'invecchiamento biologico.",
    relatedArticles: ["eta-biologica"],
  },
  {
    term: "VO2 Max",
    slug: "vo2-max",
    definition: "Il volume massimo di ossigeno che il corpo può utilizzare durante un esercizio fisico intenso. È considerato uno dei migliori indicatori di fitness cardiorespiratorio e longevità.",
    relatedArticles: ["hrv-vo2-rhr-guida", "biomarker-longevita-guida"],
  },
  {
    term: "Zeitgeber",
    slug: "zeitgeber",
    definition: "Dal tedesco 'donatore di tempo'. Qualsiasi segnale esterno (come la luce solare o il cibo) che sincronizza i ritmi biologici dell'organismo con il ciclo di 24 ore della Terra.",
    relatedArticles: ["ritmo-circadiano-master-clock"],
  },
  {
    term: "Zona 2",
    slug: "zona-2",
    definition: "Allenamento a bassa intensità (60-70% della frequenza cardiaca massima) che migliora la funzione mitocondriale e la capacità di ossidare i grassi. Fondamentale per la salute metabolica e la longevità.",
    relatedArticles: ["hrv-vo2-rhr-guida", "esercizio-massimizzare-risultati", "zona-2-allenamento-longevita"],
  },
  {
    term: "Glicina",
    slug: "glicina",
    definition: "Un amminoacido che agisce come neurotrasmettitore rilassante nel cervello. È fondamentale per la produzione di collagene, il sonno e la disintossicazione.",
    relatedArticles: ["guida-integratori"],
  },
  {
    term: "L-Teanina",
    slug: "l-teanina",
    definition: "Un amminoacido presente nel tè verde che promuove il rilassamento senza sonnolenza. Aumenta le onde alfa cerebrali e lavora in sinergia con la caffeina per migliorare la concentrazione.",
    relatedArticles: ["guida-integratori"],
  },
  {
    term: "Magnesio Bisglicinato",
    slug: "magnesio-bisglicinato",
    definition: "Una forma di magnesio legata all'amminoacido glicina. È altamente assorbibile e delicato sullo stomaco. Ideale per favorire il rilassamento, il sonno e il recupero muscolare.",
    relatedArticles: ["guida-integratori", "12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Adenosina",
    slug: "adenosina",
    definition: "Un neurotrasmettitore che si accumula nel cervello durante la veglia, creando la 'pressione del sonno'. Viene eliminata durante il sonno. La caffeina agisce bloccando i recettori dell'adenosina.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Journaling",
    slug: "journaling",
    definition: "La pratica di scrivere regolarmente pensieri, sentimenti ed esperienze. È uno strumento potente per la gestione dello stress, l'elaborazione emotiva e il miglioramento della salute mentale.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Melatonina",
    slug: "melatonina",
    definition: "L'ormone che regola il ciclo sonno-veglia. Prodotta dalla ghiandola pineale in risposta al buio, segnala al corpo che è ora di dormire. La luce blu (schermi) ne inibisce la produzione.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia", "ritmo-circadiano-master-clock"],
  },
  {
    term: "REM",
    slug: "rem",
    definition: "Rapid Eye Movement. La fase del sonno caratterizzata da sogni vividi, paralisi muscolare e attività cerebrale simile alla veglia. È cruciale per la memoria, l'apprendimento e la regolazione emotiva.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Respirazione 4-7-8",
    slug: "respirazione-4-7-8",
    definition: "Una tecnica di respirazione rilassante: inspira per 4 secondi, trattieni per 7, espira per 8. Attiva il sistema nervoso parasimpatico, riducendo ansia e favorendo il sonno.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Sistema Nervoso Parasimpatico",
    slug: "sistema-nervoso-parasimpatico",
    definition: "La parte del sistema nervoso autonomo responsabile delle funzioni di 'riposo e digestione'. Rallenta il battito cardiaco, stimola la digestione e promuove il rilassamento e il recupero.",
    relatedArticles: ["respirazione-biologia-scienza", "hrv-vo2-rhr-guida"],
  },
  {
    term: "Sonno Profondo",
    slug: "sonno-profondo",
    definition: "O sonno a onde lente (NREM fase 3). La fase più rigenerativa del sonno, in cui avviene il recupero fisico, la riparazione dei tessuti, la pulizia del cervello (sistema glinfatico) e il rilascio dell'ormone della crescita.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Zona 5",
    slug: "zona-5",
    definition: "Allenamento ad altissima intensità (90-100% della frequenza cardiaca massima), tipico dell'HIIT. Utile per migliorare il VO2 Max e la potenza cardiaca.",
    relatedArticles: ["hrv-vo2-rhr-guida", "esercizio-massimizzare-risultati"],
  },
  {
    term: "Ferritina",
    slug: "ferritina",
    definition: "Una proteina che immagazzina il ferro nelle cellule. Livelli troppo bassi indicano carenza di ferro (anemia), mentre livelli troppo alti possono indicare infiammazione o sovraccarico di ferro.",
    relatedArticles: ["analisi-sangue-longevita-guida"],
  },
  {
    term: "Fisetina",
    slug: "fisetina",
    definition: "Un polifenolo vegetale (presente nelle fragole) che agisce come potente senolitico, eliminando le cellule senescenti e riducendo l'infiammazione.",
    relatedArticles: ["integratori-senolitici-2026"],
  },
  {
    term: "Healthspan",
    slug: "healthspan",
    definition: "La durata della vita trascorsa in buona salute, liberi da malattie croniche e disabilità. È il vero obiettivo della medicina della longevità, contrapposto al semplice Lifespan.",
    relatedArticles: ["healthspan-vs-lifespan-italia"],
  },
  {
    term: "Lifespan",
    slug: "lifespan",
    definition: "La durata totale della vita di un organismo, dalla nascita alla morte, indipendentemente dalla qualità della salute in quegli anni.",
    relatedArticles: ["healthspan-vs-lifespan-italia"],
  },
  {
    term: "Mitofagia",
    slug: "mitofagia",
    definition: "Una forma specifica di autofagia che prende di mira e degrada i mitocondri danneggiati o disfunzionali, permettendo la loro sostituzione con mitocondri nuovi ed efficienti.",
    relatedArticles: ["integratori-senolitici-2026", "esercizio-massimizzare-risultati"],
  },
  {
    term: "Rapamicina",
    slug: "rapamicina",
    definition: "Un farmaco immunosoppressore che inibisce mTOR. È considerato uno dei potenziali geroprotettori più promettenti, anche se il suo uso nell'uomo per la longevità è ancora sperimentale e controverso.",
    relatedArticles: ["il-caso-bryan-johnson-rapamicina"],
  },
  {
    term: "Flessibilità Metabolica",
    slug: "flessibilita-metabolica",
    definition: "La capacità del corpo di passare efficientemente dall'uso di carboidrati a quello di grassi come fonte di energia, a seconda della disponibilità e dell'intensità dell'esercizio.",
    relatedArticles: ["zona-2-allenamento-longevita", "insulina-resistenza-metabolismo"],
  },
  {
    term: "Lattato",
    slug: "lattato",
    definition: "Un sottoprodotto del metabolismo del glucosio prodotto durante l'esercizio intenso. Non è un rifiuto, ma un carburante. La sua concentrazione nel sangue (soglia del lattato) segna il confine tra Zona 2 e intensità superiori.",
    relatedArticles: ["zona-2-allenamento-longevita"],
  },
  {
    term: "Miochine",
    slug: "miochine",
    definition: "Molecole di segnalazione (citochine) rilasciate dalle cellule muscolari durante la contrazione. Hanno effetti antinfiammatori e benefici su cervello, ossa e metabolismo.",
    relatedArticles: ["sarcopenia-forza-over-50", "esercizio-massimizzare-risultati"],
  },
  {
    term: "Sarcopenia",
    slug: "sarcopenia",
    definition: "La progressiva perdita di massa muscolare, forza e funzione legata all'invecchiamento. È un fattore di rischio primario per fragilità, cadute e mortalità precoce.",
    relatedArticles: ["sarcopenia-forza-over-50"],
  },
  {
    term: "Spermidina",
    slug: "spermidina",
    definition: "Una poliammina naturale che stimola l'autofagia, il processo di pulizia cellulare. Si trova in alimenti come il germe di grano, i funghi e i formaggi stagionati.",
    relatedArticles: ["integratori-senolitici-2026"],
  },
  {
    term: "Urolitina A",
    slug: "urolitina-a",
    definition: "Un metabolita prodotto dai batteri intestinali a partire dagli ellagitannini (melograno, noci). È noto per attivare la mitofagia e migliorare la funzione muscolare.",
    relatedArticles: ["integratori-senolitici-2026"],
  },
  {
    term: "ATP",
    slug: "atp",
    definition: "Adenosina Trifosfato. La 'moneta energetica' universale delle cellule. Ogni processo biologico — dalla contrazione muscolare alla sintesi proteica — richiede ATP. I mitocondri sono i principali produttori.",
    relatedArticles: ["esercizio-massimizzare-risultati", "luce-rossa-fotobiomodulazione-generale"],
  },
  {
    term: "BCAA",
    slug: "bcaa",
    definition: "Branched-Chain Amino Acids (Amminoacidi a Catena Ramificata). Un gruppo di tre amminoacidi essenziali (leucina, isoleucina, valina) coinvolti nella sintesi proteica muscolare e nel recupero post-esercizio.",
    relatedArticles: ["guida-integratori", "proteine-integratori-costo-beneficio"],
  },
  {
    term: "CBT-I",
    slug: "cbt-i",
    definition: "Cognitive Behavioral Therapy for Insomnia (Terapia Cognitivo-Comportamentale per l'Insonnia). Un protocollo strutturato considerato il trattamento di prima linea per l'insonnia cronica, più efficace e duraturo dei farmaci.",
    relatedArticles: ["cbt-i-insonnia", "12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "EEG",
    slug: "eeg",
    definition: "Elettroencefalogramma. Una tecnica di misurazione dell'attività elettrica del cervello tramite elettrodi posizionati sul cuoio capelluto. Rileva le onde cerebrali (Alpha, Beta, Theta, Delta, Gamma).",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "HPA",
    slug: "hpa",
    definition: "Asse Ipotalamo-Ipofisi-Surrene (Hypothalamic-Pituitary-Adrenal). Il sistema neuroendocrino che regola la risposta allo stress attraverso il rilascio di cortisolo. La sua iperattivazione cronica è alla base di molti disturbi metabolici e mentali.",
    relatedArticles: ["cortisolo-stress-cronico"],
  },
  {
    term: "TRE",
    slug: "tre",
    definition: "Time-Restricted Eating (Alimentazione a Tempo Ristretto). Una forma di digiuno intermittente che limita l'assunzione di cibo a una finestra temporale giornaliera (tipicamente 8-12 ore), allineandosi al ritmo circadiano per ottimizzare il metabolismo.",
    relatedArticles: ["digiuno-intermittente-autofagia", "pilastri-salute-80-20"],
  },
].sort((a, b) => a.term.localeCompare(b.term));

const glossaryTermsEn: GlossaryTerm[] = [
  {
    term: "AGEs",
    slug: "ages",
    definition: "Advanced Glycation End-products. Harmful compounds formed when proteins or fats bind to sugar in the blood. They contribute to aging and chronic diseases.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "ApoB",
    slug: "apob",
    definition: "Apolipoprotein B. The main protein found in 'bad' cholesterol particles (LDL, VLDL). Considered a more accurate indicator of cardiovascular risk than LDL cholesterol alone.",
    relatedArticles: ["biomarker-longevita-guida"],
  },
  {
    term: "Autophagy",
    slug: "autofagia",
    definition: "A cellular 'cleanup' process where the cell degrades and recycles its own damaged or unnecessary components. Essential for cellular renewal and longevity.",
    relatedArticles: ["digiuno-intermittente-autofagia", "dieta-mima-digiuno-fmd"],
  },
  {
    term: "Blue Zones",
    slug: "blue-zones",
    definition: "Regions of the world (like Sardinia or Okinawa) where people live significantly longer than average. Studies of these zones have revealed common longevity habits.",
    relatedArticles: [],
  },
  {
    term: "Ketones",
    slug: "chetoni",
    definition: "Molecules produced by the liver from fats when glucose availability is low (fasting, ketogenic diet). They provide efficient energy for the brain and body.",
    relatedArticles: ["digiuno-intermittente-autofagia"],
  },
  {
    term: "Cortisol",
    slug: "cortisolo",
    definition: "A steroid hormone produced by the adrenal glands in response to stress. Chronically elevated levels can negatively affect metabolism, the immune system and mental health.",
    relatedArticles: ["cortisolo-stress-cronico", "ritmo-circadiano-master-clock"],
  },
  {
    term: "Dysbiosis",
    slug: "disbiosi",
    definition: "An imbalance in the composition or function of the microbiome, often associated with gastrointestinal disorders, inflammation and other conditions.",
    relatedArticles: ["gut-health-microbioma", "microbioma"],
  },
  {
    term: "EPOC",
    slug: "epoc",
    definition: "Excess Post-exercise Oxygen Consumption. The phenomenon where the body continues to burn calories at an elevated rate even after exercise ends, to restore physiological balance.",
    relatedArticles: ["esercizio-massimizzare-risultati"],
  },
  {
    term: "EVOO",
    slug: "evoo",
    definition: "Extra Virgin Olive Oil. The highest quality olive oil, extracted without heat or chemicals. Rich in polyphenols and healthy monounsaturated fats.",
    relatedArticles: ["dieta-mima-digiuno-schema-5-giorni"],
  },
  {
    term: "FMD",
    slug: "fmd",
    definition: "Fasting Mimicking Diet. A low-calorie, low-protein dietary protocol designed to induce the beneficial effects of fasting (such as autophagy) while still eating.",
    relatedArticles: ["dieta-mima-digiuno-fmd"],
  },
  {
    term: "Fructose",
    slug: "fruttosio",
    definition: "A simple sugar naturally found in fruit. Unlike glucose, it is metabolized almost exclusively by the liver. Excess fructose (from added sugars) can cause fatty liver.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "GABA",
    slug: "gaba",
    definition: "Gamma-Aminobutyric Acid. The main inhibitory neurotransmitter in the brain, responsible for relaxation and reducing neuronal excitability.",
    relatedArticles: ["gut-health-microbioma", "12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Glycation",
    slug: "glicazione",
    definition: "A process where excess sugar in the blood binds to proteins, damaging them and compromising their function. One of the main causes of tissue aging.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "Glucose",
    slug: "glucosio",
    definition: "The primary energy source for the body's cells. Transported in the blood, its concentration is regulated by insulin.",
    relatedArticles: ["miti-zuccheri", "insulina-resistenza-metabolismo"],
  },
  {
    term: "GLUT4",
    slug: "glut4",
    definition: "A protein that transports glucose from the blood into muscle and fat cells. Exercise can activate GLUT4 independently of insulin.",
    relatedArticles: ["insulina-resistenza-metabolismo", "esercizio-massimizzare-risultati"],
  },
  {
    term: "HbA1c",
    slug: "hba1c",
    definition: "Glycated Hemoglobin. A test that measures the average blood sugar levels over the past 3 months, providing a long-term view of glycemic control.",
    relatedArticles: ["biomarker-longevita-guida", "insulina-resistenza-metabolismo"],
  },
  {
    term: "HIIT",
    slug: "hiit",
    definition: "High Intensity Interval Training. A form of cardiovascular training that alternates short periods of intense anaerobic exercise with less intense recovery periods.",
    relatedArticles: ["esercizio-massimizzare-risultati", "hrv-vo2-rhr-guida"],
  },
  {
    term: "HOMA-IR",
    slug: "homa-ir",
    definition: "Homeostatic Model Assessment for Insulin Resistance. An index used to estimate insulin resistance and pancreatic beta cell function.",
    relatedArticles: ["insulina-resistenza-metabolismo"],
  },
  {
    term: "HRV",
    slug: "hrv",
    definition: "Heart Rate Variability. The variation in the time interval between consecutive heartbeats. A key indicator of the autonomic nervous system's state and recovery.",
    relatedArticles: ["hrv-vo2-rhr-guida", "gadget-sonno-tracker"],
  },
  {
    term: "hs-CRP",
    slug: "hs-crp",
    definition: "High-sensitivity C-reactive Protein. A protein produced by the liver that increases in the presence of inflammation. The high-sensitivity version is used to assess cardiovascular risk.",
    relatedArticles: ["biomarker-longevita-guida"],
  },
  {
    term: "IGF-1",
    slug: "igf-1",
    definition: "Insulin-like Growth Factor 1. A hormone similar to insulin that regulates cell growth. Reduced levels are associated with greater longevity in many model organisms.",
    relatedArticles: ["dieta-mima-digiuno-fmd", "miti-proteine"],
  },
  {
    term: "Glycemic Index",
    slug: "indice-glicemico",
    definition: "A value indicating how quickly a carbohydrate-containing food raises blood glucose levels compared to pure glucose.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "Insulin Resistance",
    slug: "insulina-resistenza",
    definition: "A condition where the body's cells don't respond adequately to insulin, leading to elevated blood glucose levels and increasing the risk of type 2 diabetes.",
    relatedArticles: ["insulina-resistenza-metabolismo"],
  },
  {
    term: "De novo Lipogenesis",
    slug: "lipogenesi-de-novo",
    definition: "The metabolic process by which the liver converts excess carbohydrates (especially fructose) into new fatty acids, contributing to fatty liver disease.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "MACs",
    slug: "macs",
    definition: "Microbiota Accessible Carbohydrates. Complex carbohydrates (fiber) that are not digested by the host but are fermentable by gut bacteria, promoting a healthy microbiome.",
    relatedArticles: ["gut-health-microbioma", "miti-fibre"],
  },
  {
    term: "MED",
    slug: "med",
    definition: "Minimum Effective Dose. The concept of finding the minimum amount of a stimulus (such as exercise or a supplement) needed to achieve the desired result, maximizing efficiency and reducing unnecessary stress.",
    relatedArticles: ["esercizio-massimizzare-risultati"],
  },
  {
    term: "Microbiome",
    slug: "microbioma",
    definition: "The collection of microorganisms (bacteria, viruses, fungi) living in a given environment, such as the human gut. It plays a crucial role in digestion, the immune system and vitamin synthesis.",
    relatedArticles: ["microbioma", "gut-health-microbioma"],
  },
  {
    term: "Mitochondria",
    slug: "mitocondri",
    definition: "The 'power plants' of cells. Organelles responsible for energy production (ATP). Their health and efficiency decline with age but can be enhanced through exercise and diet.",
    relatedArticles: ["esercizio-massimizzare-risultati", "hrv-vo2-rhr-guida"],
  },
  {
    term: "mTOR",
    slug: "mtor",
    definition: "Mammalian Target of Rapamycin. A protein that acts as a central nutrient sensor, regulating cell growth and protein synthesis. Its inhibition is linked to autophagy and longevity.",
    relatedArticles: ["dieta-mima-digiuno-fmd", "miti-proteine"],
  },
  {
    term: "NAD+",
    slug: "nad-plus",
    definition: "Nicotinamide Adenine Dinucleotide. An essential coenzyme present in all living cells. Crucial for energy metabolism and sirtuin activity. Its levels decline with age.",
    relatedArticles: [],
  },
  {
    term: "NAFLD",
    slug: "nafld",
    definition: "Non-Alcoholic Fatty Liver Disease. Fat accumulation in the liver not caused by alcohol, often due to excess fructose and insulin resistance.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "Vagus Nerve",
    slug: "nervo-vago",
    definition: "The tenth cranial nerve and the main component of the parasympathetic nervous system. It connects the brain to the heart, lungs and gut, regulating heart rate, digestion and inflammation.",
    relatedArticles: ["respirazione-biologia-scienza", "hrv-vo2-rhr-guida"],
  },
  {
    term: "Alpha Waves",
    slug: "onde-alpha",
    definition: "Brain waves (8-13 Hz) associated with a state of relaxed wakefulness, calm and light 'flow'. Activated by closing your eyes and relaxing.",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "Beta Waves",
    slug: "onde-beta",
    definition: "Brain waves (13-30 Hz) typical of active wakefulness, focused attention and logical thinking. If excessive, they can indicate anxiety.",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "Delta Waves",
    slug: "onde-delta",
    definition: "Slow brain waves (0.5-4 Hz) dominant during deep dreamless sleep. Essential for physical regeneration and growth hormone release.",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "Gamma Waves",
    slug: "onde-gamma",
    definition: "The fastest brain waves (30-100 Hz), associated with peak concentration, insight, complex learning and memory.",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "Theta Waves",
    slug: "onde-theta",
    definition: "Brain waves (4-8 Hz) linked to deep relaxation, meditation, creativity and the REM phase of sleep.",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "ORAC",
    slug: "orac",
    definition: "Oxygen Radical Absorbance Capacity. A method of measuring the antioxidant capacity of foods and biological substances.",
    relatedArticles: ["cibi-processati-impatto"],
  },
  {
    term: "Hormesis",
    slug: "ormesi",
    definition: "A biological phenomenon where exposure to low doses of a stressor (such as cold, heat or exercise) stimulates beneficial adaptive responses that strengthen the organism.",
    relatedArticles: ["sauna-longevita-calore"],
  },
  {
    term: "Nitric Oxide",
    slug: "ossido-nitrico",
    definition: "A gaseous molecule produced in the paranasal sinuses (and in the endothelium). A potent vasodilator that improves oxygen absorption and has antimicrobial properties.",
    relatedArticles: ["respirazione-biologia-scienza"],
  },
  {
    term: "Polyphenols",
    slug: "polifenoli",
    definition: "Natural compounds found in plants with potent antioxidant and anti-inflammatory properties. Many polyphenols also act as prebiotics.",
    relatedArticles: ["gut-health-microbioma"],
  },
  {
    term: "Prebiotics",
    slug: "prebiotici",
    definition: "Non-digestible substances (often fibers) that selectively stimulate the growth and/or activity of one or more bacteria in the colon, improving host health.",
    relatedArticles: ["gut-health-microbioma"],
  },
  {
    term: "Probiotics",
    slug: "probiotici",
    definition: "Live microorganisms that, when administered in adequate amounts, confer a health benefit to the host.",
    relatedArticles: ["gut-health-microbioma", "guida-integratori"],
  },
  {
    term: "Free Radicals",
    slug: "radicali-liberi",
    definition: "Unstable molecules produced during metabolism or from external factors (pollution, UV rays). They can damage cells (oxidative stress) if not neutralized by antioxidants.",
    relatedArticles: ["cibi-processati-impatto"],
  },
  {
    term: "RHR",
    slug: "rhr",
    definition: "Resting Heart Rate. The number of heartbeats per minute when the body is at complete rest. A lower RHR generally indicates better cardiovascular efficiency.",
    relatedArticles: ["hrv-vo2-rhr-guida"],
  },
  {
    term: "Sucrose",
    slug: "saccarosio",
    definition: "Common table sugar. A disaccharide composed of one glucose molecule and one fructose molecule bonded together.",
    relatedArticles: ["miti-zuccheri"],
  },
  {
    term: "SCFA",
    slug: "scfa",
    definition: "Short Chain Fatty Acids. Produced by bacterial fermentation of fiber in the gut. Essential for colon health and metabolism.",
    relatedArticles: ["gut-health-microbioma", "miti-fibre"],
  },
  {
    term: "SCN",
    slug: "scn",
    definition: "Suprachiasmatic Nucleus. A small region of the hypothalamus that acts as the body's 'master clock', coordinating circadian rhythms in response to light.",
    relatedArticles: ["ritmo-circadiano-master-clock"],
  },
  {
    term: "Cellular Senescence",
    slug: "senescenza-cellulare",
    definition: "A state where cells stop dividing but don't die. These 'zombie cells' accumulate damage and secrete inflammatory substances that harm nearby tissues.",
    relatedArticles: [],
  },
  {
    term: "Metabolic Syndrome",
    slug: "sindrome-metabolica",
    definition: "A cluster of conditions (high blood pressure, high blood sugar, excess abdominal fat, abnormal cholesterol) that increase the risk of heart disease, stroke and diabetes.",
    relatedArticles: ["miti-zuccheri", "insulina-resistenza-metabolismo"],
  },
  {
    term: "Sirtuins",
    slug: "sirtuine",
    definition: "A family of proteins (SIRT1-7) that regulate cellular health, DNA repair and metabolism. Their activity is stimulated by NAD+ and practices like fasting.",
    relatedArticles: ["dieta-mima-digiuno-fmd"],
  },
  {
    term: "Oxidative Stress",
    slug: "stress-ossidativo",
    definition: "An imbalance between free radical production and the body's ability to neutralize them with antioxidants. A key cause of aging and many diseases.",
    relatedArticles: ["miti-zuccheri", "cibi-processati-impatto"],
  },
  {
    term: "Telomeres",
    slug: "telomeri",
    definition: "The protective caps at the ends of chromosomes. They shorten each time a cell divides, and their length is considered an indicator of biological aging.",
    relatedArticles: ["eta-biologica"],
  },
  {
    term: "VO2 Max",
    slug: "vo2-max",
    definition: "The maximum volume of oxygen the body can use during intense exercise. Considered one of the best indicators of cardiorespiratory fitness and longevity.",
    relatedArticles: ["hrv-vo2-rhr-guida", "biomarker-longevita-guida"],
  },
  {
    term: "Zeitgeber",
    slug: "zeitgeber",
    definition: "German for 'time giver'. Any external signal (such as sunlight or food) that synchronizes the body's biological rhythms with the Earth's 24-hour cycle.",
    relatedArticles: ["ritmo-circadiano-master-clock"],
  },
  {
    term: "Zone 2",
    slug: "zona-2",
    definition: "Low-intensity training (60-70% of maximum heart rate) that improves mitochondrial function and fat oxidation capacity. Essential for metabolic health and longevity.",
    relatedArticles: ["hrv-vo2-rhr-guida", "esercizio-massimizzare-risultati", "zona-2-allenamento-longevita"],
  },
  {
    term: "Glycine",
    slug: "glicina",
    definition: "An amino acid that acts as a relaxing neurotransmitter in the brain. Essential for collagen production, sleep and detoxification.",
    relatedArticles: ["guida-integratori"],
  },
  {
    term: "L-Theanine",
    slug: "l-teanina",
    definition: "An amino acid found in green tea that promotes relaxation without drowsiness. Increases alpha brain waves and works synergistically with caffeine to improve focus.",
    relatedArticles: ["guida-integratori"],
  },
  {
    term: "Magnesium Bisglycinate",
    slug: "magnesio-bisglicinato",
    definition: "A form of magnesium bound to the amino acid glycine. Highly absorbable and gentle on the stomach. Ideal for promoting relaxation, sleep and muscle recovery.",
    relatedArticles: ["guida-integratori", "12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Adenosine",
    slug: "adenosina",
    definition: "A neurotransmitter that builds up in the brain during waking hours, creating 'sleep pressure'. It is cleared during sleep. Caffeine works by blocking adenosine receptors.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Journaling",
    slug: "journaling",
    definition: "The practice of regularly writing down thoughts, feelings and experiences. A powerful tool for stress management, emotional processing and improving mental health.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Melatonin",
    slug: "melatonina",
    definition: "The hormone that regulates the sleep-wake cycle. Produced by the pineal gland in response to darkness, it signals the body that it's time to sleep. Blue light (screens) inhibits its production.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia", "ritmo-circadiano-master-clock"],
  },
  {
    term: "REM",
    slug: "rem",
    definition: "Rapid Eye Movement. The sleep phase characterized by vivid dreams, muscle paralysis and brain activity similar to waking. Crucial for memory, learning and emotional regulation.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "4-7-8 Breathing",
    slug: "respirazione-4-7-8",
    definition: "A relaxation breathing technique: inhale for 4 seconds, hold for 7, exhale for 8. Activates the parasympathetic nervous system, reducing anxiety and promoting sleep.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Parasympathetic Nervous System",
    slug: "sistema-nervoso-parasimpatico",
    definition: "The part of the autonomic nervous system responsible for 'rest and digest' functions. It slows the heart rate, stimulates digestion and promotes relaxation and recovery.",
    relatedArticles: ["respirazione-biologia-scienza", "hrv-vo2-rhr-guida"],
  },
  {
    term: "Deep Sleep",
    slug: "sonno-profondo",
    definition: "Or slow-wave sleep (NREM stage 3). The most regenerative sleep phase, where physical recovery, tissue repair, brain cleansing (glymphatic system) and growth hormone release occur.",
    relatedArticles: ["12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "Zone 5",
    slug: "zona-5",
    definition: "Very high intensity training (90-100% of maximum heart rate), typical of HIIT. Useful for improving VO2 Max and cardiac output.",
    relatedArticles: ["hrv-vo2-rhr-guida", "esercizio-massimizzare-risultati"],
  },
  {
    term: "Ferritin",
    slug: "ferritina",
    definition: "A protein that stores iron in cells. Levels that are too low indicate iron deficiency (anemia), while levels that are too high can indicate inflammation or iron overload.",
    relatedArticles: ["analisi-sangue-longevita-guida"],
  },
  {
    term: "Fisetin",
    slug: "fisetina",
    definition: "A plant polyphenol (found in strawberries) that acts as a potent senolytic, eliminating senescent cells and reducing inflammation.",
    relatedArticles: ["integratori-senolitici-2026"],
  },
  {
    term: "Healthspan",
    slug: "healthspan",
    definition: "The length of time a person lives in good health, free from chronic diseases and disabilities. It is the true goal of longevity medicine, as opposed to simple Lifespan.",
    relatedArticles: ["healthspan-vs-lifespan-italia"],
  },
  {
    term: "Lifespan",
    slug: "lifespan",
    definition: "The total length of an organism's life, from birth to death, regardless of the quality of health during those years.",
    relatedArticles: ["healthspan-vs-lifespan-italia"],
  },
  {
    term: "Mitophagy",
    slug: "mitofagia",
    definition: "A specific form of autophagy that targets and degrades damaged or dysfunctional mitochondria, allowing them to be replaced with new, efficient ones.",
    relatedArticles: ["integratori-senolitici-2026", "esercizio-massimizzare-risultati"],
  },
  {
    term: "Rapamycin",
    slug: "rapamicina",
    definition: "An immunosuppressant drug that inhibits mTOR. Considered one of the most promising potential geroprotectors, although its use in humans for longevity is still experimental and controversial.",
    relatedArticles: ["il-caso-bryan-johnson-rapamicina"],
  },
  {
    term: "Metabolic Flexibility",
    slug: "flessibilita-metabolica",
    definition: "The body's ability to efficiently switch between using carbohydrates and fats as energy sources, depending on availability and exercise intensity.",
    relatedArticles: ["zona-2-allenamento-longevita", "insulina-resistenza-metabolismo"],
  },
  {
    term: "Lactate",
    slug: "lattato",
    definition: "A byproduct of glucose metabolism produced during intense exercise. It is not waste, but fuel. Its concentration in the blood (lactate threshold) marks the boundary between Zone 2 and higher intensities.",
    relatedArticles: ["zona-2-allenamento-longevita"],
  },
  {
    term: "Myokines",
    slug: "miochine",
    definition: "Signaling molecules (cytokines) released by muscle cells during contraction. They have anti-inflammatory effects and benefits for the brain, bones, and metabolism.",
    relatedArticles: ["sarcopenia-forza-over-50", "esercizio-massimizzare-risultati"],
  },
  {
    term: "Sarcopenia",
    slug: "sarcopenia",
    definition: "The progressive loss of muscle mass, strength, and function linked to aging. It is a primary risk factor for frailty, falls, and early mortality.",
    relatedArticles: ["sarcopenia-forza-over-50"],
  },
  {
    term: "Spermidine",
    slug: "spermidina",
    definition: "A natural polyamine that stimulates autophagy, the cellular cleanup process. Found in foods like wheat germ, mushrooms, and aged cheeses.",
    relatedArticles: ["integratori-senolitici-2026"],
  },
  {
    term: "Urolithin A",
    slug: "urolitina-a",
    definition: "A metabolite produced by gut bacteria from ellagitannins (pomegranate, walnuts). Known for activating mitophagy and improving muscle function.",
    relatedArticles: ["integratori-senolitici-2026"],
  },
  {
    term: "ATP",
    slug: "atp",
    definition: "Adenosine Triphosphate. The universal 'energy currency' of cells. Every biological process — from muscle contraction to protein synthesis — requires ATP. Mitochondria are the primary producers.",
    relatedArticles: ["esercizio-massimizzare-risultati", "luce-rossa-fotobiomodulazione-generale"],
  },
  {
    term: "BCAA",
    slug: "bcaa",
    definition: "Branched-Chain Amino Acids. A group of three essential amino acids (leucine, isoleucine, valine) involved in muscle protein synthesis and post-exercise recovery.",
    relatedArticles: ["guida-integratori", "proteine-integratori-costo-beneficio"],
  },
  {
    term: "CBT-I",
    slug: "cbt-i",
    definition: "Cognitive Behavioral Therapy for Insomnia. A structured protocol considered the first-line treatment for chronic insomnia, more effective and longer-lasting than medication.",
    relatedArticles: ["cbt-i-insonnia", "12-consigli-pratici-sonno-insonnia"],
  },
  {
    term: "EEG",
    slug: "eeg",
    definition: "Electroencephalogram. A technique for measuring the brain's electrical activity through electrodes placed on the scalp. It detects brain waves (Alpha, Beta, Theta, Delta, Gamma).",
    relatedArticles: ["binaural-beats-onde-cerebrali"],
  },
  {
    term: "HPA",
    slug: "hpa",
    definition: "Hypothalamic-Pituitary-Adrenal axis. The neuroendocrine system that regulates the stress response through cortisol release. Its chronic overactivation underlies many metabolic and mental health disorders.",
    relatedArticles: ["cortisolo-stress-cronico"],
  },
  {
    term: "TRE",
    slug: "tre",
    definition: "Time-Restricted Eating. A form of intermittent fasting that limits food intake to a daily window (typically 8-12 hours), aligning with the circadian rhythm to optimize metabolism.",
    relatedArticles: ["digiuno-intermittente-autofagia", "pilastri-salute-80-20"],
  },
].sort((a, b) => a.term.localeCompare(b.term))

export function getAllGlossaryTerms(locale: string = 'it'): GlossaryTerm[] {
  if (locale === 'en' && glossaryTermsEn.length > 0) {
    return glossaryTermsEn;
  }
  return glossaryTermsIt;
}

export function getGlossaryTermBySlug(slug: string, locale: string = 'it'): GlossaryTerm | undefined {
  const terms = getAllGlossaryTerms(locale);
  return terms.find((term) => term.slug === slug);
}
