[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/ingest/static/*"
  to = "https://us-assets.i.posthog.com/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ingest/*"
  to = "https://us.i.posthog.com/:splat"
  status = 200
  force = true
